[package]
name = "vanhouzen-site"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8"
axum-htmx = "0.7"
dotenvy = "0.15"
fastrace = { version = "0.7", features = ["enable"] }
fastrace-axum = "0.1"
log = "0.4"
maud = { version = "0.27", features = ["axum"] }
tokio = { version = "1.44", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.6", features = ["fs", "tracing"] }
tower-livereload = "0.9"
